spring.application.name=bookmanager
#H2 database
#in memory database
spring.datasource.url=jdbc:h2:mem:bookdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
#JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#automatically creates tables from my models.
spring.jpa.hibernate.ddl-auto=update
#show SQL in console(optional)
spring.jpa.show-sql=true
#H2 console (to view database at /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console